name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /public_html/a/

          exclude: |
            **/.git*
            **/.env
            **/vendor/**
            **/node_modules/**
            **/storage/**
            **/tests/**
            **/.github/**
            **/README.md